zyambo/models/models.py
from zyambo.app import app, db

zyambo/__init__.py
# #!/usr/bin/env python3
# """ Entr point"""
# from flask import Flask, abort, jsonify, render_template
# from zyambo.views import app_views

# app = Flask(__name__)
# app.register_blueprint(app_views)


# @app.errorhandler(404)
# def not_found(error: str) -> str:
#     """ Page not found error"""
#     return render_template('error.html', error=error), 404

# @app.errorhandler(401)
# def unauthorized(error: str) -> str:
#     """ unauthorized error"""
#     return render_template('error.html', error=error), 401


# if __name__ == "__main__":
#      app.jinja_env.auto_reload = True
#      app.config['TEMPLATES_AUTO_RELOAD'] = True
#      app.run(debug=True, host='0.0.0.0')

zyambo/app.py
#!/usr/bin/env python3
""" Entr point"""
from flask import Flask, render_template
from zyambo.views import app_views
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_sqlalchemy import SQLAlchemy


app = Flask(__name__)
app.register_blueprint(app_views)
app.config["CACHE_TYPE"] = "null"

# Create in-memory database
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///sample_db.sqlite'
app.config['SQLALCHEMY_ECHO'] = True
db = SQLAlchemy(app)

# set optional bootswatch theme
app.config['FLASK_ADMIN_SWATCH'] = 'cerulean'
app.config['SECRET_KEY'] = 'zyambossecret'


# Create models
class Project(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(80), unique=False)
    github_url = db.Column(db.String(244), unique=False)
    hosted_url = db.Column(db.String(244), unique=False)
    description = db.Column(db.String(244), unique=False)
    date = db.Column(db.DateTime)


class MyContact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(80), unique=True)
    mobile1 = db.Column(db.String(80), unique=True)
    mobile2 = db.Column(db.String(80), unique=True)


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    email = db.Column(db.String(120), unique=True)

    # Required for administrative interface
    def __unicode__(self):
        return self.username


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(120))
    text = db.Column(db.Text, nullable=False)
    date = db.Column(db.DateTime)

    user_id = db.Column(db.Integer(), db.ForeignKey(User.id))
    user = db.relationship(User, backref='posts')

    def __unicode__(self):
        return self.title
    
@app.errorhandler(404)
def PageNotFound(error: str) -> str:
    """ Page not found error"""
    return render_template('error.html', error=error), 404

@app.errorhandler(405)
def methodNotAllowed(error: str) -> str:
    """ unauthorized error"""
    return render_template('error.html', error=error), 405


admin = Admin(app, name='Zyambo admin', template_mode='bootstrap4')
admin.add_view(ModelView(User, db.session))
admin.add_view(ModelView(Post, db.session))
admin.add_view(ModelView(Project, db.session))
admin.add_view(ModelView(MyContact, db.session))


if __name__ == "__main__":
    app.jinja_env.auto_reload = True
    app.config['TEMPLATES_AUTO_RELOAD'] = True
    # Create DB
    with app.app_context():
        db.create_all()

    app.run(debug=False, host='0.0.0.0')

zyambo/views/__init__.py
#!/usr/bin/env python3
""" Blueprint
"""
from flask import Blueprint

app_views = Blueprint("app_views", __name__, url_prefix="/")

from zyambo.views.about import *
from zyambo.views.contact import *
from zyambo.views.index import *
from zyambo.views.project import *
from zyambo.views.portfolio import *
from zyambo.views.lipila import *
from zyambo.views.quote import *
from zyambo.views.zma import *
from zyambo.views.zpi import *
from zyambo.views.zep import *
from zyambo.views.zms import *
from zyambo.views.zse import *

zyambo/views/about.py
""" about view"""
from zyambo.views import app_views
from flask import jsonify, render_template
from datetime import datetime

@app_views.route('/zyambo/about/', methods=['GET'], strict_slashes=False)
def about() -> str:
    """ about route
    """
    return render_template('about.html', title='Summary')

zyambo/views/contact.py
""" contact view"""
from zyambo.views import app_views
from flask import jsonify, render_template

@app_views.route('/zyambo/contact', methods=['GET', 'POST'], strict_slashes=False)
def contact() -> str:
    """ contact route
    """
    return render_template('contact.html')

zyambo/views/index.py
""" index view"""
from zyambo.views import app_views
from flask import jsonify, render_template, url_for

@app_views.route("/", methods=['GET'], strict_slashes=False)
def index() -> str:
    """ Index route
    """
    return render_template('index.html')

@app_views.route("/status", methods=['GET'], strict_slashes=False)
def status() -> str:
    """ Index route
    """
    return jsonify({'Status': 'OK'}), 200

zyambo/views/lipila.py
""" lipila view"""
from zyambo.views import app_views
from flask import render_template

@app_views.route('/zyambo/projects/lipila', methods=['GET'], strict_slashes=False)
def lipila() -> str:
    """ lipila project route
    """
    return render_template('lipila.html')

zyambo/views/portfolio.py
# portfolio view

from zyambo.views import app_views
from flask import jsonify, render_template

@app_views.route("/zyambo/portfolio/", methods=['GET'], strict_slashes=False)
def portfolio() -> str:
    """
    route to list previous industries and projects
    """
    return render_template('portfolio.html')

zyambo/views/project.py
""" project view"""
# if __name__=="__main__":
from zyambo.views import app_views
from flask import render_template
# from zyambo.app import Project

@app_views.route("/zyambo/projects/", methods=['GET', 'POST'], strict_slashes=False)
def projects() -> str:
    """ projects route
    """
    # models = Project.query.all()  # Fetch data
    # print(models)
    return render_template('projects.html')

zyambo/views/quote.py
# portfolio view

from zyambo.views import app_views
from flask import jsonify, render_template

@app_views.route("/zyambo/estimate-price/", methods=['GET', 'POST'], strict_slashes=False)
def quote() -> str:
    """
    route to estimate price
    """
    return render_template('quote.html')

zyambo/views/zep.py
""" about view"""
from zyambo.views import app_views
from flask import jsonify, render_template
from datetime import datetime

@app_views.route('/zyambo/business/', methods=['GET'], strict_slashes=False)
def business() -> str:
    """ 
    My entrepreneurial journey
    """
    return render_template('zep.html', title='Zyambo Business')

zyambo/views/zma.py
""" about view"""
from zyambo.views import app_views
from flask import jsonify, render_template
from datetime import datetime

@app_views.route('/zyambo/martial-arts/', methods=['GET'], strict_slashes=False)
def martial_arts() -> str:
    """ 
    My Martial Arts journey
    """
    return render_template('zma.html', title='Zyambo Martial Arts')

zyambo/views/zms.py
""" about view"""
from zyambo.views import app_views
from flask import jsonify, render_template
from datetime import datetime

@app_views.route('/zyambo/music/', methods=['GET'], strict_slashes=False)
def music() -> str:
    """ 
    My Music journey
    """
    return render_template('zms.html', title='Zyambo Music')

zyambo/views/zpi.py
""" about view"""
from zyambo.views import app_views
from flask import jsonify, render_template
from datetime import datetime

@app_views.route('/zyambo/private-investigator/', methods=['GET'], strict_slashes=False)
def private_investigator() -> str:
    """ 
    My Pi journey
    """
    return render_template('zpi.html', title='Zyambo Private-Investigator')

zyambo/views/zse.py
""" about view"""
from zyambo.views import app_views
from flask import jsonify, render_template
from datetime import datetime

@app_views.route('/zyambo/software-engineer/', methods=['GET'], strict_slashes=False)
def software_engineer() -> str:
    """ 
    My SE journey
    """
    return render_template('zse.html', title='Zyambo Software Engineer')

zyambo/templates/about.html
{% extends 'base.html'%}
{% block title%} {{title}}{%endblock%}
{% block content%}
<div class="terminal">
    <div class="container about">
        <div class="row">
            <div class="col-md-6">
                <img src="{{url_for('static', filename='/img/pz.JPG')}}" class="profile-img"
                    alt="zyambo img">
            </div>
            <h2 class=""> &#9745; {{ title }}</h2>
                <p class="bio-desc"> I am a multifaceted professional with a diverse range of passions and expertise. As the founder of Pesa Consulting and Investigations (PESA), I have provided investigative services to clients worldwide, honing my skills in analysis, problem-solving, and attention to detail. My entrepreneurial spirit led me to establish <a href="https://lipila.tech">Lipila Technologies Limited</a>, a software company dedicated to creating innovative solutions that address real-world challenges. As a software engineer, I thrive on turning ideas into reality through code, leveraging technology to drive efficiency and growth. Beyond the tech world, I am a passionate musician, performing as a pianist and teaching students to discover the joy of music. Additionally, as a martial artist trained in Kyokushin Karate and Kung Fu, I embrace the discipline and resilience of these practices, both as a practitioner and an instructor. Each of these roles reflects my commitment to continuous growth, innovation, and making a positive impact in the world. </p>
            </div>
        </div>
    </div>
</div>
{% endblock%}

zyambo/templates/api.html
{% extends 'base.html'%}
{% block content%}
<h1>API page under construction</h1>
{% endblock%}

zyambo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{%block title%}{%endblock%}</title>
    <!-- meta info -->
    <!-- <meta charset="UTF-8"> -->
    <meta charset="UTF-8">
    <meta title="Peter Sangwani Zyambo">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"
        content="Private Investigator, Software Engineer, Martial Artist, Musician, Polymath">
    <meta name="author" content="Peter Sangwani Zyambo">
    <meta name="keywords"
        content="Martial Arts, Private Investigator, Software Engineer, Musician, Polymath">
    <!-- stylesheet -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/slides.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/more-styles.css') }}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <!-- icon -->
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='img/pz.ico') }}" />
    <!-- js -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

    <script src="{{url_for('static', filename='js/script.js')}}"></script>

</head>

<body onload="typeWriter();" class="home" id="container">
    <a class="nav-link" href="{{url_for('app_views.index')}}"><img class="logo-img"
            src="{{url_for('static', filename='/img/pz.png')}}" alt="zyambo'a logo"></a>
    <div class="intro">
        <h1 id="name">Peter Zyambo</h1>
        <p id="job">Polymath</p>
    </div>
    <nav class="navbar navbar-expand-md navbar-light">
        <a class="nav-brand" href="{{url_for('app_views.index')}}"><span class="bio-txt">pz</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{{url_for('app_views.index')}}">Home </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('app_views.business')}}">Entreprenuer</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('app_views.private_investigator')}}">Private Investigator</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('app_views.martial_arts')}}">Martial Artist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('app_views.software_engineer')}}">Software Engineer</a>

                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('app_views.music')}}">Musician</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{{url_for('app_views.about')}}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('app_views.contact')}}">Get in Touch</a>

                </li>
            </ul>
        </div>
    </nav>
    <section class="custom-section">
        {% block content %}
        {% endblock %}
    </section>
    <hr>
    <section class="social-section">
        <div class="social">
            <a href="https://www.linkedin.com/in/zyambo" class="fa fa-linkedin fa-32x" target="__blank">linkedin</a><span> </span>
            <a href="https://www.twitter.com/peter_zyambo" class="fa fa-twitter" target="__blank">twitter</a><span> </span>
            <a href="https://www.github.com/sangwani-coder" class="fa fa-github" target="__blank">github</a>
        </div>
    </section>
    <section class="footer-section">
        <!-- <footer> Copyright &copy 2022 Peter S. Zyambo.</footer> -->
        <h3 class="tag "><span id="tag-dev">Designed and Developed by</span> <span class="tag-pz">Peter Zyambo</span>
        </h3>
    </section>
</body>

</html>

zyambo/templates/contact.html
{% extends 'base.html'%}
{% block title%} Zyambo Contact Me{%endblock%}
{% block content%}
<div class="terminal">
    <h2>Contact Info:</h2>
    <div class="terminal-one">
        <h6>Email: zyambopeter1@gmail.com</h6>
        <h6>Call: +260-965-604-023</h6>
        <h6>Address: Zambia, Africa</h6>
    </div>

</div>


{% endblock%}

zyambo/templates/error.html
{%extends 'base.html'%}

{% block title%}- Error!{%endblock%}
{%block content%}
<div class="terminal">
    <div class="projects">
        <p style="color: white;">{{error}}</p>
    </div>

</div>
{% endblock%}

zyambo/templates/index.html
{% extends "base.html" %}
{% block title%} Peter Sangwani Zyambo{%endblock%}
{% block content %}
<div class="bio terminal">
    <a href="{{url_for('app_views.about')}}" id="pz" class="link-anchor"><h2 class="heading">Hello, I'm Zyambo</h2></a>
    <a href="https://lipila.tech" class="zoom"><p id="bio"></p><span class="bio-txt">bio</span></a>
</div>
<hr>
<div class="home-projects">
    <a href="{{url_for('app_views.about')}}" class="btn btn-primary">Read More</a>
</div>
{% endblock %}

zyambo/templates/portfolio.html
{% extends 'base.html'%}
{% block title%} Zyambo Hobbies with Income {%endblock%}
{% block content%}
<div class="terminal">
    <div class="container freelancing-page">
        <h1 class="heading">My Hobbies that earn income</h1>
        <div class="row">
            <div class="col-md-4 text-wrap">
                <h2 class="job-head">Piano Teaching</h2>
                <h6>From beginners to advanced students:</h6>
                <ul>
                    <li>I teach classical piano to students from age 5</li>
                    <li>Organize recitals for my students</li>
                    <li>Prepare students for ABRSM Piano exams</li>
                </ul>
            </div>
                        
            <div class="col-md-4 text-wrap">
                <h2 class="job-head">Martial Arts</h2>
                <h6>Discipline, focus, and self-defense skills for everyone. I offer:</h6>
                <ul>
                    <li>I Practice Kung-fu, Kyokushin Karate and Kickboxing</li>
                    <li>Martial arts training for both kids and adults</li>
                    <li>Self-defense instruction for personal safety and empowerment</li>
                </ul>
            </div>
            <div class="col-md-4 text-wrap">
                <h2 class="job-head">Music Performance</h2>
                <h6>From stately halls to intimate gatherings, I bring the magic of music to every occasion. My
                    experience includes:</h6>
                <ul>
                    <li>My Major instruments are Piano, Trumpet and Guitar</li>
                    <li>Performing at state and corporate functions</li>
                    <li>Adding soulful melodies to weddings and special events</li>
                    <li>Teaching private music lessons to nurture budding musicians</li>
                </ul>
            </div>
        </div>
        
        <h6 class="call-to-action">Ready to collaborate? <a href="{{url_for('app_views.contact')}}"
                class="btn btn-primary">Contact Me</a> me today to discuss your project needs.</h6>
    </div>
    {% endblock%}

zyambo/templates/zep.html
{% extends 'base.html'%}
{% block title%} {{title}}{%endblock%}
{% block content%}
<div class="terminal">
    <div class="container about">
        <div class="row">
            <div class="col-md-6">
                <img src="{{url_for('static', filename='/img/biz.jpg')}}" class="profile-img"
                    alt="zyambo img">
            </div>
            <h2 class=""> &#9745; {{ title }}</h2>
                <p class="bio-desc"> I am the founder and CEO of <a href="https://lipila.tech">Lipila Technologies Limited</a>, a software company incorporated in 2024. Lipila Technologies is dedicated to creating innovative solutions that address real-world challenges, leveraging cutting-edge technology to drive efficiency and growth. As an entrepreneur, I am passionate about building businesses that not only thrive commercially but also make a meaningful impact on society. For me, entrepreneurship is about more than just creating companies—it’s about building a legacy, one venture at a time. I strive to inspire others to embrace innovation, take risks, and pursue their dreams with determination and purpose. </p>
            </div>
        </div>
    </div>
</div>
{% endblock%}

zyambo/templates/zma.html
{% extends 'base.html'%}
{% block title%} {{title}}{%endblock%}
{% block content%}
<div class="terminal">
    <div class="container about">
        <div class="row">
            <div class="col-md-6">
                <img src="{{url_for('static', filename='/img/art.jpg')}}" class="profile-img"
                    alt="zyambo img">
            </div>
            <h2 class=""> &#9745; {{ title }}</h2>
                <p class="bio-desc"> As a martial artist, I have trained in Kyokushin Karate and Kung Fu, disciplines that have not only strengthened my body but also shaped my mind and spirit. Martial arts have taught me the values of discipline, perseverance, and respect, which I strive to embody in all aspects of my life. As an instructor, I am passionate about sharing these teachings with others, helping students build confidence, focus, and resilience through the practice of martial arts. Whether it’s through rigorous training, sparring, or teaching, I am committed to promoting the physical, mental, and spiritual benefits of martial arts to individuals and communities. </p>
            </div>
        </div>
    </div>
</div>
{% endblock%}

zyambo/templates/zms.html
{% extends 'base.html'%}
{% block title%} {{title}} {%endblock%}
{% block content%}
<div class="terminal">
    <audio controls autoplay>
    <source src="{{url_for('static', filename='/music/Beethoven.ogg')}}" type="audio/ogg">
    <source src="{{url_for('static', filename='/music/Beethoven.mp3')}}" type="audio/mpeg">
    </audio>
    <div class="container about">
        <div class="row">
            <div class="col-md-6">
                <img src="{{url_for('static', filename='/img/piano.jpg')}}" class="profile-img"
                    alt="zyambo img">
            </div>
            <h2 class="entr"> &#9745; Music Journey</h2>
                <p class="bio-desc"> Music has been a lifelong passion of mine, and as a pianist, I have had the privilege of both performing and teaching. As a performer, I have played in various settings, from intimate recitals to larger concert venues, bringing emotion and artistry to every piece I play. As a piano teacher, I am dedicated to nurturing the next generation of musicians, helping students of all ages and skill levels discover their love for music and develop their technical and expressive abilities. Music, for me, is a universal language that connects people, and I am committed to sharing its beauty and power with others. </p>
            </div>
        </div>
    </div>
</div>
{% endblock%}

zyambo/templates/zpi.html
{% extends 'base.html'%}
{% block title%} {{title}}{%endblock%}
{% block content%}
<div class="terminal">
    <div class="container about">
        <div class="row">
            <div class="col-md-6">
                <img src="{{url_for('static', filename='/img/biz.jpg')}}" class="profile-img"
                    alt="zyambo img">
            </div>
            <h2 class=""> &#9745; {{ title }}</h2>
                <p class="bio-desc"> I am the founder of Pesa Consulting and Investigations (PESA), a private investigations firm that began operations in 2014 and was officially registered in 2016. Under PESA, I have provided investigative services to clients across the globe, including South Africa, Kenya, Egypt, Ivory Coast, Panama, Taiwan, Ireland, the USA, the UK, Switzerland, China, and more. Our clientele ranges from individuals and private investigators to small businesses and multinational corporations. My work as a private investigator has honed my attention to detail, analytical thinking, and problem-solving skills, enabling me to uncover truths and deliver results in complex and high-stakes situations. </p>
            </div>
        </div>
    </div>
</div>
{% endblock%}

zyambo/templates/zse.html
{% extends 'base.html'%}
{% block title%} {{title}}{%endblock%}
{% block content%}
<div class="terminal">
    <div class="container about">
        <div class="row">
            <div class="col-md-6">
                <img src="{{url_for('static', filename='/img/biz.jpg')}}" class="profile-img"
                    alt="zyambo img">
            </div>
            <h2 class=""> &#9745; {{ title }}</h2>
                <p class="bio-desc"> As a software engineer, I bring a blend of technical expertise and creative problem-solving to every project I undertake. With a strong foundation in programming, system design, and software development, I have worked on a wide range of applications, from web and mobile platforms to enterprise-level systems. My passion for technology drives me to continuously learn and adapt to new tools and methodologies, ensuring that I deliver efficient, scalable, and user-friendly solutions. Whether it’s writing clean code, debugging complex systems, or collaborating with cross-functional teams, I thrive on turning ideas into reality through the power of software. </p>
            </div>
        </div>
    </div>
</div>
{% endblock%}